version: '3'

services:
  postgres:
    image: postgres
    shm_size: '4gb'  # Poprawiono błąd składniowy: zmieniono 'shm_zise' na 'shm_size'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"  # Poprawiono błąd składniowy: dodano cudzysłów do portu
    volumes:
      - postgres:/var/lib/postgresql/data  # Poprawiono błąd składniowy: poprawiono literówkę w nazwie woluminu

volumes:
  postgres:
    driver: local
