@url = http://localhost:5000
@reservationId = a3fa63cd-44c8-4337-b239-d4d6bfb640b4

@parkingSpotId1 = 00000000-0000-0000-0000-000000000001

###
GET {{url}}

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}

### 
POST  {{url}}/reservations
Content-Type: application/json

{
    "ParkingSpotId": "{{parkingSpotId1}}",
    "EmployeeName" : "John Doe",
    "LicensePlate" : "KLI0123",
    "Date" : "2024-02-23"
}

###
PUT  {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "LicensePlate" : "KLI00125"
}

###
DELETE {{url}}/reservations/{{reservationId}}